/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import people.Mecanicien;
import people.Personne;

/**
 *
 * @author student
 */

public class login extends javax.swing.JFrame {
    private Properties Login;
    
    public login(){
        initComponents();
                
        Login = new Properties();
        
        try {
            Login.load(new FileInputStream("Login.properties"));
        }
        catch (FileNotFoundException ex) {
            
            Login.setProperty("Wagner",     "abc");
            Login.setProperty("Wilvers",    "abc");
            Login.setProperty("Costa",      "abc");
            Login.setProperty("Hiard",      "abc");
            Login.setProperty("Engels",     "abc");
            Login.setProperty("Thiernesse", "abc");
            Login.setProperty("Vanstapel",  "abc");
            
            try {
                Login.store(new FileOutputStream("Login.properties"),"Table contenant les Login et Mot de Passe de tout les utilisateurs");
            }
            catch (IOException ex1) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex1);
            } 
        } catch (IOException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_User = new javax.swing.JTextField();
        TextField_Pswd = new javax.swing.JTextField();
        Label_User = new javax.swing.JLabel();
        Label_pswd = new javax.swing.JLabel();
        Button_OK = new javax.swing.JButton();
        Button_KO = new javax.swing.JButton();
        ErrorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Garage HEPL: Login");

        Label_User.setText("Utilisateur :");

        Label_pswd.setText("Mot de passe :");

        Button_OK.setText("Ok");
        Button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OKActionPerformed(evt);
            }
        });

        Button_KO.setText("Annuler");
        Button_KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KOActionPerformed(evt);
            }
        });

        ErrorMsg.setForeground(new java.awt.Color(255, 51, 51));
        ErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_User, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_Pswd, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(TextField_User))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Button_KO, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_User, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField_Pswd, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(Label_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(ErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_OK)
                    .addComponent(Button_KO))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OKActionPerformed
        String tmp;
    
        if(!TextField_User.getText().equals("")  && !TextField_Pswd.getText().equals("")){           
            //Si Membre du Personnel Sélectionner:
                tmp = Login.getProperty(TextField_User.getText() , "KO");
                if(tmp.equals(TextField_Pswd.getText())){ // si on trouve le nom d'utilisateur et que le mdp est bon
                    
                    this.setVisible(false); //Fermeture de login
                    Atelier atelier = new Atelier(); //Creation de la fenètre Atelier à la volée
                    
                    Personne PerTmp = null;
                    //Recherche de l'objet représentant l'utilisateur:
                    for (Iterator it = atelier.getContainer().getUsers().iterator(); it.hasNext();) {
                        PerTmp = (Personne) it.next();
                        if(PerTmp.getNom().equals(TextField_User.getText())){    
                            break;
                        }
                    }
                    
                    //On set l'utilisateur de l'atelier, si il n'existe pas on le crée
                    if(PerTmp != null){
                        atelier.setUser(PerTmp);
                    }
                    else{
                        PerTmp = new Mecanicien(TextField_User.getText(),"Inconnus");
                        atelier.getContainer().getUsers().add(PerTmp);
                        atelier.setUser(PerTmp);
                    }
                    
                    atelier.Log().PrintLN("Login","Login Utilisateur" + PerTmp);
                    
                    atelier.setVisible(true); //Affichage Atelier
                    this.dispose(); //Suppression Mémoire de login
                }
                else{
                    if(tmp.equals("KO")){ //Si on ne trouve pas le login
                        ErrorMsg.setText("Login Introuvable");
                    }
                    else{           //Si Mdp Incorrecte
                        ErrorMsg.setText("Mdp Incorrecte");
                    }
                }
            }
        //Si rien écris
        else ErrorMsg.setText("Encodez votre Login, Mdp et Cocher un type d'accès");        
    }//GEN-LAST:event_Button_OKActionPerformed

    private void Button_KOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KOActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Button_KOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new login().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_KO;
    private javax.swing.JButton Button_OK;
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JLabel Label_User;
    private javax.swing.JLabel Label_pswd;
    private javax.swing.JTextField TextField_Pswd;
    private javax.swing.JTextField TextField_User;
    // End of variables declaration//GEN-END:variables
}
