/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

import Container.ContainerClass;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author matteoarnone
 */
public class Atelier extends javax.swing.JFrame
{
    /**
     * Creates new form Atelier
     */
    public static final String  FilePath = "SavedEnvironment.ser";
    private ContainerClass Container;

    public void setContainer(ContainerClass Container) {
        this.Container = Container;
    }

    public ContainerClass getContainer() {
        return Container;
    }
    
    @SuppressWarnings("Convert2Lambda")
    public Atelier() {
        initComponents();
        
        //Ajout des composants de la bar de menu       
        JMenu para, aide;
        JMenuItem info,debut,apropos;
    
        MenuBar.add(Box.createHorizontalGlue());
        para = new JMenu("Paramètres");
        info = new JMenuItem("Infos système");
        para.add(info);
        
        aide = new JMenu("Aide");
        debut = new JMenuItem("Pour débuter");
        apropos = new JMenuItem("A propos de...");
        
        aide.add(debut);
        aide.addSeparator();
        aide.add(apropos);
        
        
        MenuBar.add(Box.createHorizontalGlue());
        MenuBar.add(para);
        MenuBar.add(aide);
         
        apropos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) { 
                    APropos ap = new APropos(null,true);
                    ap.setVisible(true);
                }
        });
        
        this.setDefaultCloseOperation(Atelier.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter()
            {
                @Override
                public void windowClosing(WindowEvent arg0) {
                    try {
                        SaveContainer();
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Atelier.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    System.exit(0);
                }
            });
        
        try {
            //Load Container:
            ObjectInputStream ObjectIN = new ObjectInputStream(new FileInputStream(FilePath));
            
            setContainer((ContainerClass) ObjectIN.readObject());
            ObjectIN.close();
            
        } catch (FileNotFoundException ex) {
            setContainer(new ContainerClass());
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Atelier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void SaveContainer() throws FileNotFoundException{
        try {
            ObjectOutputStream ObjectOUT = new ObjectOutputStream(new FileOutputStream(FilePath));
            ObjectOUT.writeObject(getContainer());
            ObjectOUT.close();
        } catch (IOException ex) {
            Logger.getLogger(Atelier.class.getName()).log(Level.SEVERE, null, ex);
        }      
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        Label_Atelier = new javax.swing.JLabel();
        Label_Pont1 = new javax.swing.JLabel();
        Label_Pont2 = new javax.swing.JLabel();
        Label_Pont3 = new javax.swing.JLabel();
        Label_Sol = new javax.swing.JLabel();
        Label_Divers = new javax.swing.JLabel();
        TextField_Pont1 = new javax.swing.JTextField();
        TextField_Pont2 = new javax.swing.JTextField();
        TextField_Pont3 = new javax.swing.JTextField();
        TextField_Divers = new javax.swing.JTextField();
        TextField_Sol = new javax.swing.JTextField();
        Label_Bureau = new javax.swing.JLabel();
        Label_BureauClient = new javax.swing.JLabel();
        LabelBureauClient = new javax.swing.JTextField();
        Label_BureauCompta = new javax.swing.JLabel();
        LabelPrésence = new javax.swing.JLabel();
        CheckBox_Absent = new javax.swing.JRadioButton();
        CheckBox_Present = new javax.swing.JRadioButton();
        CheckBox_Patron = new javax.swing.JCheckBox();
        CheckBox_PauseMidi = new javax.swing.JCheckBox();
        ImageFond = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        Menu_Atelier = new javax.swing.JMenu();
        MenuItem_APrevoir = new javax.swing.JMenuItem();
        MenuItem_PriseEnCharge = new javax.swing.JMenuItem();
        MenuItem_Terminé = new javax.swing.JMenuItem();
        SeparateurMenuAtelier = new javax.swing.JPopupMenu.Separator();
        MenuItem_Listes = new javax.swing.JMenuItem();
        Menu_Materiel = new javax.swing.JMenu();
        MenuItem_Commander = new javax.swing.JMenu();
        MenuItem_CommanderPièce = new javax.swing.JMenuItem();
        MenuItem_CommanderPneux = new javax.swing.JMenuItem();
        MenuItem_CommanderLubrifiants = new javax.swing.JMenuItem();
        MenuItem_Receptionner = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        MenuItem_ListeCommandes = new javax.swing.JMenuItem();
        Menu_Clients = new javax.swing.JMenu();
        Menu_Facture = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Atelier.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        Label_Atelier.setForeground(new java.awt.Color(60, 60, 60));
        Label_Atelier.setText("Atelier");
        Label_Atelier.setToolTipText("");

        Label_Pont1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Pont1.setText("Pont n°1");

        Label_Pont2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Pont2.setText("Pont n°2");

        Label_Pont3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Pont3.setText("Pont n°3");

        Label_Sol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Sol.setText("Sol");

        Label_Divers.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_Divers.setText("Divers");

        Label_Bureau.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        Label_Bureau.setText("Bureau");

        Label_BureauClient.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_BureauClient.setText("Bureau client");

        Label_BureauCompta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_BureauCompta.setText("Bureau de compatibilité");

        LabelPrésence.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        LabelPrésence.setText("Me Boulier est là");

        buttonGroup2.add(CheckBox_Absent);
        CheckBox_Absent.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CheckBox_Absent.setText("Certains absents");

        buttonGroup2.add(CheckBox_Present);
        CheckBox_Present.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CheckBox_Present.setText("Tout le monde présent");

        buttonGroup1.add(CheckBox_Patron);
        CheckBox_Patron.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CheckBox_Patron.setText("Patron disponible");

        buttonGroup1.add(CheckBox_PauseMidi);
        CheckBox_PauseMidi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CheckBox_PauseMidi.setText("Pause-midi");

        ImageFond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Screenshot 2022-05-03 at 11.24.14.png"))); // NOI18N
        ImageFond.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ImageFond.setFocusable(false);
        ImageFond.setRequestFocusEnabled(false);
        ImageFond.setVerifyInputWhenFocusTarget(false);

        MenuBar.setBackground(new java.awt.Color(242, 242, 242));
        MenuBar.setToolTipText("");

        Menu_Atelier.setText("Atelier");

        MenuItem_APrevoir.setText("A prevoir");
        MenuItem_APrevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_APrevoirActionPerformed(evt);
            }
        });
        Menu_Atelier.add(MenuItem_APrevoir);

        MenuItem_PriseEnCharge.setText("Prise en charge");
        MenuItem_PriseEnCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_PriseEnChargeActionPerformed(evt);
            }
        });
        Menu_Atelier.add(MenuItem_PriseEnCharge);

        MenuItem_Terminé.setText("Terminé");
        MenuItem_Terminé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_TerminéActionPerformed(evt);
            }
        });
        Menu_Atelier.add(MenuItem_Terminé);
        Menu_Atelier.add(SeparateurMenuAtelier);

        MenuItem_Listes.setText("Listes");
        Menu_Atelier.add(MenuItem_Listes);

        MenuBar.add(Menu_Atelier);

        Menu_Materiel.setText("Materiel");

        MenuItem_Commander.setText("Commander");

        MenuItem_CommanderPièce.setText("Commander une pièce");
        MenuItem_Commander.add(MenuItem_CommanderPièce);

        MenuItem_CommanderPneux.setText("Commander des pneus");
        MenuItem_Commander.add(MenuItem_CommanderPneux);

        MenuItem_CommanderLubrifiants.setText("Commander des lubrifiants");
        MenuItem_Commander.add(MenuItem_CommanderLubrifiants);

        Menu_Materiel.add(MenuItem_Commander);

        MenuItem_Receptionner.setText("Réceptionner");
        Menu_Materiel.add(MenuItem_Receptionner);
        Menu_Materiel.add(jSeparator4);

        MenuItem_ListeCommandes.setText("Liste commandes");
        Menu_Materiel.add(MenuItem_ListeCommandes);

        MenuBar.add(Menu_Materiel);

        Menu_Clients.setText("Clients");
        MenuBar.add(Menu_Clients);

        Menu_Facture.setText("Facture");
        MenuBar.add(Menu_Facture);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_BureauCompta)
                        .addGap(26, 26, 26)
                        .addComponent(LabelPrésence)
                        .addGap(0, 544, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_BureauClient)
                            .addComponent(Label_Bureau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(372, 372, 372)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox_PauseMidi)
                                    .addComponent(CheckBox_Patron))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBox_Absent)
                                    .addComponent(CheckBox_Present))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LabelBureauClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(TextField_Sol, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Divers, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Pont3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Pont2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextField_Pont1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImageFond)
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Sol)
                            .addComponent(Label_Divers)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Label_Pont2)
                                .addComponent(Label_Pont1))
                            .addComponent(Label_Pont3)
                            .addComponent(Label_Atelier))
                        .addContainerGap(755, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Label_Atelier)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Pont1)
                            .addComponent(TextField_Pont1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Pont2)
                            .addComponent(TextField_Pont2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Pont3)
                            .addComponent(TextField_Pont3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Sol)
                            .addComponent(TextField_Sol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Divers)
                            .addComponent(TextField_Divers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ImageFond)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckBox_Patron)
                            .addComponent(CheckBox_Present)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Label_Bureau)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_BureauClient)
                            .addComponent(LabelBureauClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_BureauCompta)
                            .addComponent(LabelPrésence)
                            .addComponent(CheckBox_PauseMidi)
                            .addComponent(CheckBox_Absent)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_APrevoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_APrevoirActionPerformed
        AtelierAPrevoir Popup = new AtelierAPrevoir(this,true);
        Popup.setVisible(true);
    }//GEN-LAST:event_MenuItem_APrevoirActionPerformed

    private void MenuItem_PriseEnChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_PriseEnChargeActionPerformed
        AtelierPriseEnCharge Popup = new AtelierPriseEnCharge(this, true);
        Popup.setVisible(true);
    }//GEN-LAST:event_MenuItem_PriseEnChargeActionPerformed

    private void MenuItem_TerminéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_TerminéActionPerformed
        AtelierTerminer Popup = new AtelierTerminer(this, true);
        Popup.setVisible(true);
    }//GEN-LAST:event_MenuItem_TerminéActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CheckBox_Absent;
    private javax.swing.JCheckBox CheckBox_Patron;
    private javax.swing.JCheckBox CheckBox_PauseMidi;
    private javax.swing.JRadioButton CheckBox_Present;
    private javax.swing.JLabel ImageFond;
    private javax.swing.JTextField LabelBureauClient;
    private javax.swing.JLabel LabelPrésence;
    private javax.swing.JLabel Label_Atelier;
    private javax.swing.JLabel Label_Bureau;
    private javax.swing.JLabel Label_BureauClient;
    private javax.swing.JLabel Label_BureauCompta;
    private javax.swing.JLabel Label_Divers;
    private javax.swing.JLabel Label_Pont1;
    private javax.swing.JLabel Label_Pont2;
    private javax.swing.JLabel Label_Pont3;
    private javax.swing.JLabel Label_Sol;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItem_APrevoir;
    private javax.swing.JMenu MenuItem_Commander;
    private javax.swing.JMenuItem MenuItem_CommanderLubrifiants;
    private javax.swing.JMenuItem MenuItem_CommanderPièce;
    private javax.swing.JMenuItem MenuItem_CommanderPneux;
    private javax.swing.JMenuItem MenuItem_ListeCommandes;
    private javax.swing.JMenuItem MenuItem_Listes;
    private javax.swing.JMenuItem MenuItem_PriseEnCharge;
    private javax.swing.JMenuItem MenuItem_Receptionner;
    private javax.swing.JMenuItem MenuItem_Terminé;
    private javax.swing.JMenu Menu_Atelier;
    private javax.swing.JMenu Menu_Clients;
    private javax.swing.JMenu Menu_Facture;
    private javax.swing.JMenu Menu_Materiel;
    private javax.swing.JPopupMenu.Separator SeparateurMenuAtelier;
    private javax.swing.JTextField TextField_Divers;
    private javax.swing.JTextField TextField_Pont1;
    private javax.swing.JTextField TextField_Pont2;
    private javax.swing.JTextField TextField_Pont3;
    private javax.swing.JTextField TextField_Sol;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        new Atelier().setVisible(true);
    }
}
