/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Container.ContainerClass;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matteoarnone
 */
public class AtelierTerminer extends javax.swing.JDialog {

    private final Atelier Parent;
    
    /**
     * Creates new form PriseEnCharge
     * @param parent
     * @param modal
     */
    
    public AtelierTerminer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //On récupère la ref vers le parent
        Parent = (Atelier) parent;
        
        RefreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Label_TravauxAttente = new javax.swing.JLabel();
        Scroll_TableListeTravaux = new javax.swing.JScrollPane();
        Table_ListeTravaux = new javax.swing.JTable();
        Bouton_KO = new javax.swing.JButton();
        Bouton_OK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Label_TravauxAttente.setText("Travaux en Cours:");

        Table_ListeTravaux.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type voiture", "Immatriculation", "Propriétaire", "Travail", "Remarques", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Scroll_TableListeTravaux.setViewportView(Table_ListeTravaux);

        Bouton_KO.setText("Annuler");
        Bouton_KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_KOActionPerformed(evt);
            }
        });

        Bouton_OK.setText("OK");
        Bouton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_OKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label_TravauxAttente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Scroll_TableListeTravaux, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(Bouton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Bouton_KO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_TravauxAttente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Scroll_TableListeTravaux, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bouton_OK)
                    .addComponent(Bouton_KO))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_KOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_KOActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bouton_KOActionPerformed

    private void Bouton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_OKActionPerformed

        DefaultTableModel model = (DefaultTableModel) Table_ListeTravaux.getModel();
        int selected;

        //Si rien cocher, alors on ne fait rien
        if((selected = Table_ListeTravaux.getSelectedRow()) == -1)
        {
            JOptionPane.showMessageDialog(this,"Veuillez sélectionner un Travail.","Erreur", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //On récupère le vecteur:
        Vector tmp = (Vector) model.getDataVector().elementAt(selected);
        Parent.getContainer().getListeTravauxEnCours().remove(selected);
        
        Parent.getContainer().getListeTravauxFini().add(tmp);

        this.dispose();
    }//GEN-LAST:event_Bouton_OKActionPerformed
        
    public void RefreshTable()
    {
        //On récupère le modèle de la table
        DefaultTableModel model = (DefaultTableModel) Table_ListeTravaux.getModel();
        for(int i = 0 ; i < Parent.getContainer().getListeTravauxEnCours().size() ; i++)
        {
            model.addRow((Vector) Parent.getContainer().getListeTravauxEnCours().get(i));
        }
        Table_ListeTravaux.setModel(model);
        model.fireTableDataChanged();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_KO;
    private javax.swing.JButton Bouton_OK;
    private javax.swing.JLabel Label_TravauxAttente;
    private javax.swing.JScrollPane Scroll_TableListeTravaux;
    private javax.swing.JTable Table_ListeTravaux;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}