/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import static people.PersonnelGarage.loginGarage;
import static people.TechnicienExterieur.loginExterieur; 
/**
 *
 * @author student
 */

public class login extends javax.swing.JFrame {
    
    /**
     * Creates new form login
     */
    private boolean trouve,garage,ext;
    private String tmp;
    
    
    
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        TextField_User = new javax.swing.JTextField();
        TextField_Pswd = new javax.swing.JTextField();
        Label_User = new javax.swing.JLabel();
        Label_pswd = new javax.swing.JLabel();
        Radio_Interne = new javax.swing.JRadioButton();
        Radio_Externe = new javax.swing.JRadioButton();
        Button_OK = new javax.swing.JButton();
        Button_KO = new javax.swing.JButton();
        ErrorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_User.setText("Utilisateur :");

        Label_pswd.setText("Mot de passe :");

        buttonGroup2.add(Radio_Interne);
        Radio_Interne.setText("Membre du personnel");

        buttonGroup2.add(Radio_Externe);
        Radio_Externe.setText("Extérieur habilité");

        Button_OK.setText("Ok");
        Button_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OKActionPerformed(evt);
            }
        });

        Button_KO.setText("Annuler");
        Button_KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KOActionPerformed(evt);
            }
        });

        ErrorMsg.setForeground(new java.awt.Color(255, 51, 51));
        ErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio_Interne))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_KO, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radio_Externe, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_User, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_Pswd, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .addComponent(TextField_User))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_User, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_User, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Radio_Interne)
                    .addComponent(Radio_Externe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_KO)
                    .addComponent(Button_OK)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OKActionPerformed
        
        if(!TextField_User.getText().equals("")  && !TextField_Pswd.getText().equals("")){
            trouve = false;
            tmp = null;
            
            //Si Membre du Personnel Sélectionner:
            if(Radio_Interne.isSelected())
            {
                for (String i : loginGarage.keySet()) 
                {
                    //Si on trouve on quitte la boucle
                    if(i.equals(TextField_User.getText()))
                    {
                        tmp = i;
                        trouve = true;
                        break;
                    }     
                }
                
                if(trouve)
                {                    
                    if(loginGarage.get(tmp).equals(TextField_Pswd.getText()))
                    {
                         this.setVisible(false); //Fermeture de login
                         Atelier Interne = new Atelier(); //Creation de la fenètre Atelier à la volée
                         Interne.setVisible(true); //Affichage Atelier
                         this.dispose(); //Suppression Mémoire de login
                    }
                    else ErrorMsg.setText("Mdp Incorrecte");
                }
                else ErrorMsg.setText("Login Introuvable");
            }
            
            //Si Externe Sélectionner:
            if(Radio_Externe.isSelected())
            {
                for (String i : loginExterieur.keySet()) 
                {
                    //Si on trouve on quitte la boucle
                    if(i.equals(TextField_User.getText())){
                        tmp = i;
                        trouve = true;
                        break;
                    }
                }
                
                if(trouve)
                {
                    if(loginExterieur.get(tmp).equals(TextField_Pswd.getText()))
                    {
                        this.setVisible(false); //Fermeture de login
                        Atelier Externe = new Atelier(); //Creation de la fenètre Atelier à la volée
                        Externe.setVisible(true); //Affichage Atelier
                        this.dispose(); //Suppression Mémoire de login
                    }
                    else ErrorMsg.setText("Mdp Incorrecte");
                }
                else ErrorMsg.setText("Login Introuvable");

            }            
        }
        //Si rien écris
        else ErrorMsg.setText("Encodez votre Login, Mdp et Cocher un type d'accès");        
    }//GEN-LAST:event_Button_OKActionPerformed

    private void Button_KOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KOActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Button_KOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new login().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_KO;
    private javax.swing.JButton Button_OK;
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JLabel Label_User;
    private javax.swing.JLabel Label_pswd;
    private javax.swing.JRadioButton Radio_Externe;
    private javax.swing.JRadioButton Radio_Interne;
    private javax.swing.JTextField TextField_Pswd;
    private javax.swing.JTextField TextField_User;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables
}
