/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Paramètre;

import GUI.Atelier;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;


/**
 *
 * @author student
 */
public class ChoixFormatDate extends javax.swing.JDialog {
    
    Atelier Parent;
    
    /**
     * Creates new form ChoixFormatDate
     */
    public ChoixFormatDate(Atelier parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Parent = parent;
        
        Vector tmp = Parent.getContainer().getEtatFormat();
        
        if(tmp != null){
            this.jComboBox_Local.setSelectedIndex((int) tmp.get(0));
            this.jComboBox_Temps.setSelectedIndex((int) tmp.get(1));
            this.jComboBox_Calendrier.setSelectedIndex((int) tmp.get(2));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_Local = new javax.swing.JComboBox<>();
        jComboBox_Temps = new javax.swing.JComboBox<>();
        jComboBox_Calendrier = new javax.swing.JComboBox<>();
        jButton_OK = new javax.swing.JButton();
        jButton_KO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choix du Format de la Date");

        jLabel2.setText("Local :");

        jLabel4.setText("Format Temporel :");

        jLabel6.setText("Format Calendrier :");

        jComboBox_Local.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Royaume Uni", "Allemagne", "Italie", "USA" }));

        jComboBox_Temps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "hh : mm", "hh : mm : ss" }));

        jComboBox_Calendrier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jj/mm/aa", "jj/mm/aaaa", "mm/jj/aa", "NomJour  jj, Mois aaaa" }));

        jButton_OK.setText("Enregistrer");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_KO.setText("Annuler");
        jButton_KO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_OK)
                                .addGap(54, 54, 54)
                                .addComponent(jButton_KO, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox_Local, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_Calendrier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_Temps, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_Temps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox_Calendrier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK)
                    .addComponent(jButton_KO))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        Vector state = new Vector();
        
        Locale locale = null;
        String TempsFormat = null;
        String DateFormat = null;
        
        switch(this.jComboBox_Local.getSelectedIndex()){
            case 0:
                locale = Locale.FRENCH;
                break;
            case 1:
                locale = Locale.ENGLISH;
                break;
            case 2:
                locale = Locale.GERMAN;
                break;
            case 3:
                locale = Locale.ITALIAN;
                break;
            case 4:
                locale = Locale.ENGLISH;
                break;
            default:
                System.out.println("Erreur, Choix Inconnu Local: " + this.jComboBox_Local.getSelectedIndex());
                System.exit(100);
        }
        
        switch(this.jComboBox_Temps.getSelectedIndex()){
            case 0:
                TempsFormat = "HH:mm";
                break;
            case 1:
                TempsFormat = "HH:mm:ss";
                break;
            default:
                System.out.println("Erreur, Choix Inconnu Temps: " + this.jComboBox_Temps.getSelectedIndex());
                System.exit(100);
        }
        
        switch(this.jComboBox_Calendrier.getSelectedIndex()){
            case 0:
                DateFormat = "dd/MM/yy";
                break;
            case 1:
                DateFormat = "dd/MM/yyyy";
                break;
            case 2:
                DateFormat = "MM/dd/yy";
                break;
            case 3:
                DateFormat = "EEEE dd, MMMM yyyy";
                break;
                
            default:
                System.out.println("Erreur, Choix Inconnu Calendrier: " + this.jComboBox_Calendrier.getSelectedIndex());
                System.exit(100);
        }
        
        //Au sauvegarde l'état de la fenètre
        state.add(this.jComboBox_Local.getSelectedIndex());
        state.add(this.jComboBox_Temps.getSelectedIndex());
        state.add(this.jComboBox_Calendrier.getSelectedIndex());
        
        Parent.getContainer().setEtatFormat(state);
        
        //On set le format dans Atelier
        Parent.getContainer().setDateformat(new SimpleDateFormat(DateFormat + " | " + TempsFormat, locale));
        
        this.dispose();
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_KOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KOActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_KOActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_KO;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JComboBox<String> jComboBox_Calendrier;
    private javax.swing.JComboBox<String> jComboBox_Local;
    private javax.swing.JComboBox<String> jComboBox_Temps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
